"use client"
import NavBar from '@/components/NavBar';
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer';
import { Provider } from 'react-redux';
import { Inter } from 'next/font/google';
import { store } from '@/Redux/store';
import { useState } from 'react';
import Cart from '@/components/Cart'
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Cosmetics Web',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [showCart,setShowCart]=useState(false)
  return (
    <html lang="en">
      <head>
      <title>Cosmetics Web</title>
      <link rel="shortcut icon" href="/favicon.ico" sizes="any" />
        <meta name='description' content='Generated by create next app' />
        </head>
      <body className={inter.className}>
        <Provider store={store}>
        <NavBar setShowCart={setShowCart}/>
        {showCart && <Cart setShowCart={setShowCart}/>}
        {children}
        <Footer/>
        </Provider>
        </body>
    </html>
  )
}
